language: ruby
rvm:
- '2.3.1'
- '2.4.2'
sudo: false
cache: bundler
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
addons:
  postgresql: '9.4'
install:
  - bin/setup
  - git fetch origin hawkular-1328 && git branch hawkular-1328 FETCH_HEAD
  - gem install pronto-rubocop
script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pronto run -c hawkular-1328; fi
  - bundle exec rake
after_script: bundle exec codeclimate-test-reporter
